/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Equipo
 */
public class AdminGeneros extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public AdminGeneros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMainNuevo = new javax.swing.JButton();
        btnMainEliminar = new javax.swing.JButton();
        lblBuscar3 = new javax.swing.JLabel();
        lblBuscar4 = new javax.swing.JLabel();
        panelTxtBuscar4 = new javax.swing.JPanel();
        txtBuscar4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnMainEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva Referencia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 245, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generos");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 380, 50));

        btnMainNuevo.setBackground(new java.awt.Color(204, 204, 204));
        btnMainNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMainNuevo.setText("Nueva");
        jPanel1.add(btnMainNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 35));

        btnMainEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnMainEliminar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMainEliminar.setText("Eliminar");
        btnMainEliminar.setToolTipText("");
        jPanel1.add(btnMainEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 90, 35));

        lblBuscar3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblBuscar3.setForeground(new java.awt.Color(51, 51, 51));
        lblBuscar3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBuscar3.setText("Lista");
        lblBuscar3.setToolTipText("");
        jPanel1.add(lblBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        lblBuscar4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblBuscar4.setForeground(new java.awt.Color(51, 51, 51));
        lblBuscar4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBuscar4.setText("Generos");
        lblBuscar4.setToolTipText("");
        jPanel1.add(lblBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

        panelTxtBuscar4.setBackground(new java.awt.Color(255, 255, 255));
        panelTxtBuscar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelTxtBuscar4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtBuscar4.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscar4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar4.setToolTipText("");
        txtBuscar4.setBorder(null);
        panelTxtBuscar4.add(txtBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 1, 200, 20));

        jPanel1.add(panelTxtBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, 22));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 210, 25));

        btnMainEliminar1.setBackground(new java.awt.Color(204, 204, 204));
        btnMainEliminar1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMainEliminar1.setText("Editar");
        btnMainEliminar1.setToolTipText("");
        jPanel1.add(btnMainEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 90, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGeneros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainEliminar;
    private javax.swing.JButton btnMainEliminar1;
    private javax.swing.JButton btnMainNuevo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuscar3;
    private javax.swing.JLabel lblBuscar4;
    private javax.swing.JPanel panelTxtBuscar4;
    private javax.swing.JTextField txtBuscar4;
    // End of variables declaration//GEN-END:variables
}
