/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Equipo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        ((DefaultTableCellRenderer) tablaEmpleados.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer rendar = new DefaultTableCellRenderer();
        rendar.setHorizontalAlignment(jLabel1.CENTER);
        tablaEmpleados.getColumnModel().getColumn(0).setCellRenderer(rendar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        panelTxtBuscar = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnMainNuevo = new javax.swing.JButton();
        btnMainVer = new javax.swing.JButton();
        btnMainEditar = new javax.swing.JButton();
        btnMainEliminar = new javax.swing.JButton();
        scrollTabla = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Empleados");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 250, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Lista de Empleados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 136, 27));

        lblBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(51, 51, 51));
        lblBuscar.setText("Buscar");
        lblBuscar.setToolTipText("");
        jPanel1.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 35, -1, -1));

        panelTxtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        panelTxtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelTxtBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar.setToolTipText("");
        txtBuscar.setBorder(null);
        panelTxtBuscar.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 1, 140, 20));

        jPanel1.add(panelTxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 150, 25));

        btnMainNuevo.setBackground(new java.awt.Color(204, 204, 204));
        btnMainNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMainNuevo.setText("Nuevo");
        jPanel1.add(btnMainNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 90, 35));

        btnMainVer.setBackground(new java.awt.Color(204, 204, 204));
        btnMainVer.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMainVer.setText("Ver");
        jPanel1.add(btnMainVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 90, 35));

        btnMainEditar.setBackground(new java.awt.Color(204, 204, 204));
        btnMainEditar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMainEditar.setText("Editar");
        jPanel1.add(btnMainEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 90, 35));

        btnMainEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnMainEliminar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnMainEliminar.setText("Eliminar");
        jPanel1.add(btnMainEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 90, 35));

        tablaEmpleados.setAutoCreateRowSorter(true);
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nº Documento", "Nombre Completo", "Dirección", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleados.setRowHeight(25);
        tablaEmpleados.setSelectionBackground(new java.awt.Color(59, 105, 165));
        tablaEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaEmpleados.setShowVerticalLines(false);
        scrollTabla.setViewportView(tablaEmpleados);
        if (tablaEmpleados.getColumnModel().getColumnCount() > 0) {
            tablaEmpleados.getColumnModel().getColumn(0).setMinWidth(150);
            tablaEmpleados.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaEmpleados.getColumnModel().getColumn(0).setMaxWidth(150);
            tablaEmpleados.getColumnModel().getColumn(3).setMinWidth(150);
            tablaEmpleados.getColumnModel().getColumn(3).setPreferredWidth(50);
            tablaEmpleados.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        jPanel1.add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 860, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainEditar;
    private javax.swing.JButton btnMainEliminar;
    private javax.swing.JButton btnMainNuevo;
    private javax.swing.JButton btnMainVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel panelTxtBuscar;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
